// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package proto;

public final class HelloWorldProto {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_helloworld_HelloRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_helloworld_HelloRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_helloworld_HelloReply_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_helloworld_HelloReply_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\013hello.proto\022\nhelloworld\"-\n\014HelloReques" +
                        "t\022\014\n\004name\030\001 \001(\t\022\017\n\007sleepOn\030\002 \001(\005\"\035\n\nHell" +
                        "oReply\022\017\n\007message\030\001 \001(\t2I\n\007Greeter\022>\n\010Sa" +
                        "yHello\022\030.helloworld.HelloRequest\032\026.hello" +
                        "world.HelloReply\"\000B \n\005protoB\017HelloWorldP" +
                        "rotoP\001\242\002\003HLWb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_helloworld_HelloRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_helloworld_HelloRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_helloworld_HelloRequest_descriptor,
                new String[]{"Name", "SleepOn",});
        internal_static_helloworld_HelloReply_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_helloworld_HelloReply_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_helloworld_HelloReply_descriptor,
                new String[]{"Message",});
    }

    private HelloWorldProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
