// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package proto;

public interface HelloRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:helloworld.HelloRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    String getName();

    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>int32 sleepOn = 2;</code>
     */
    int getSleepOn();
}
